// Auto generated by @nuxt/eslint
// if import has error run dev command to generate .nuxt
// @ts-check
import withNuxt from './.nuxt/eslint.config.mjs';

export default withNuxt();
// Your custom configs here
