name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  spec:
    name: Spec
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'
      - name: setup node
        uses: 'actions/setup-node@v4'
        with:
          node-version: '22.x'
      - run: npm ci
      - run: npm run spec:unit
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: [spec]
    steps:
      - uses: 'actions/checkout@v4'
      - name: Setup node
        uses: 'actions/setup-node@v4'
        with:
          node-version: '22.x'
      - run: npm ci
      - run: npm run lint
